export default function imgSrc(shopifyImgSrc) {
  // Temporarily remove existing query string so that url generated by nuxt-img works.
  // https://github.com/nuxt/image/issues/319
  return shopifyImgSrc.split('?')[0].replace('https://cdn.shopify.com', '')
}
